### ISSUE TITLE
Each export creates a new Service Principal

### ISSUE THREAD

**Issue by JimmyKarlsson1** [Azure/manage-azure-policy#43]
When exporting to Github repo with the same location, a new service principal is always created. It would be helpful if either the same service principal is identified or there were an option to use an already existing service principal (and workflow file)

**Comment by JCDeist** [comment]
I agree with this. Being able to update existing workflow files would be extremely useful. Especially in the case of initiatives. Right now If I want to add an additional policy to an existing initiative. I have to export the entire initiative again, create a new workflow and service principal user. Then we have to delete the old service principal user and workflow.

**Comment by ds-ms** [comment]
We would run into prediction issues if we reuse an existing workflow or SPN.

Let's say, in your first export you exported `Policy1` and `Policy2`. Your SPN would have specific permissions on these both policies. Now in your next go, you were to export `Policy2` and `Policy3`. 
Because we can't read your repo secrets, we won't be able to allow your existing SPN to have permissions on `Policy3`. 
Also, this keeps us good on the security front, because of the limited permissions and no extra bookkeeping of your SPNs lying around anywhere. 

The recommendation of export feature is, once you do your export; you use your repo for updating your policies avoiding you from re-exporting the same policies.

**Comment by JCDeist** [comment]
In the scenario you outlined, what would be the recommended workflow for adding a new custom policy to an existing initiative assignment? Say we have initiative1 which contains policy1 and policy2 as well as assignment1.  If we want to add policy3 to this initiative, would we create and export policy3 creating workflow2?  Then update assignment1 to include policy3? This would force us to have to run workflow1 and workflow2 to make sure the initiative is up to date after any changes?  
I have not found a way to create policy3 within github and then update workflow1 to create policy3, is this possible?

**Comment by Ganeshrockz** [comment]
@JCDeist Add your `policy3`'s definition inside the exported `policyset.json` file and trigger the workflow. If you want it to be added in a different scope you would need to manually create an SPN and scope it down to your requirements. Since initiative assignments are scoped by the initiative definition id I believe that they should be applicable to the newly created policy definition. This should solve your problem I guess. Please let me know if I missing something

**Comment by JCDeist** [comment]
@Ganeshrockz are you stating to next the entire policy definition within the policyset? The issue I am seeing here is that the {policyset.json} relies on ResourceIDs, so in this situation I would have to first make sure that {policy3} exists in order to obtain a ResourceID to place into the {policyset.json}.  It is not an issue of scope but just determining a way to keep the initiative related to only 1 workflow while being able to add additional policies to that workflow.

**Comment by ajinkya599** [comment]
> I have not found a way to create policy3 within github and then update workflow1 to create policy3, is this possible?

Yes, it is possible to do so. You can add the definition for `policy3` in your repo. (The `id` should be unique and the policy file should be called `policy.json`).
You can then add another step in your workflow(before the step to update the initiative) to create/update `policy3`, something like this:
```yaml
- name: Create or Update Policy3
      uses: azure/manage-azure-policy@v0
      with:
        # policy3 is defined in the file policies/custom/policy3/policy.json
        paths: |
          policies/custom/policy3/**
```

You may want to use this step to manage all the policies present in your initiative.
@JCDeist  - Does this answer your question?

**Comment by JCDeist** [comment]
This process did work for me. 1. Create `policy3` 2. save policy definition in the repository 3. update `policyset.json` 4. update the workflow file to include the policy.

I appreciate the responses.

**Comment by ds-ms** [comment]
Closing stale issue, feel free to reopen if this problem still persists.
